language: java
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
    - name: "Linux JDK8 Test R,python,bash"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        - NO_TEST_CMD=1
      jdk:
        - openjdk8
#    - name: "Linux JDK11"
#      os: linux
#      dist: xenial
#      jdk:
#        - openjdk11
#      env:
#        - TRAVIS_DIST_NAME="xenial"
#        - NO_TEST_R=1
#        - NO_TEST_PYTHON=1
#        - NO_TEST_BASH=1
#        - NO_TEST_CMD=1
#    - name: "Linux JDK11 Test R,python,bash"
#      os: linux
#      dist: xenial
#      env:
#        - TRAVIS_DIST_NAME="xenial"
#        - NO_TEST_JAVA=1
#        - NO_TEST_CMD=1
#      jdk:
#        - openjdk11
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
    - name: "MacOS JDK8 Test R,python,bash"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        - NO_TEST_CMD=1
#    - name: "MacOS JDK11"
#      os: osx
#      osx_image: xcode10.1
#      env:
#        - global: JAVA_OPTS=-Xmx4g
#    - name: "Windows" --- Not yet supported
#      os: windows
#      jdk:
#        - oraclejdk8
#        - oraclejdk11
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - git clone https://github.com/Funz/funz-core
  - cd funz-core
  - ant dist
  - cd ..
  - git clone https://github.com/Funz/funz-calculator
  - cd funz-calculator
  - ant dist
  - cd ..
  - cd $WD
  - export ANT_OPTS="-Xmx2g -XX:MaxPermSize=512m"
#  - ant dist

before_script:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install r; fi
  - if [[ "$TRAVIS_OSX_IMAGE" == "xcode9.3" ]]; then brew upgrade python; fi # to get python3 instead of 2 -> ok.py test working
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [[ "$TRAVIS_DIST_NAME" == "trusty" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_DIST_NAME" == "xenial" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-recommended -y; fi
  - if [[ "$NO_TEST_PYTHON" != "1" ]]; then if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; brew install numpy; pip3 install py4j;  fi; if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python3-numpy python3-pip; pip3 install py4j; fi; fi
  - if [[ "$NO_TEST_R" != "1" ]]; then sudo ln -s /usr/lib/jvm/default-java $JAVA_HOME; sudo R CMD javareconf; sudo R -e "install.packages('rJava')"; fi

script:
  - ant dist
  - ant test

after_success:
  - if [[ "$NO_TEST_JAVA" != "1" ]]; then ant coverage ; fi
  - if [[ "$NO_TEST_JAVA" != "1" ]]; then bash <(curl -s https://codecov.io/bash) ; fi

before_deploy:
  - mv dist Funz
  - zip -r funz-client.zip Funz

deploy:
  provider: releases
  name: funz_client
  api_key:
    secure: E6RhJ6bvS8g9UZiCJUh31jqAJ0p6M1JMVqUrV1wKDbn7ua0oiDvM33e39vRhIUaTtsPcCVV9qzC7D4oU+VXhDa6/r3ZRrTBEwsOJ8A5y7DB8V2reKZ+4MweiJVGbj6Wky0bU/bbZQtJec+hSxOqFXbbnhgMC9H2fQRnB6JaPfMXIhpDfHpcKxbdHDowaoP40Oidwf0YCAb9EeEuCKehuJ4yR/lksCLYUYRKrNOEYv5E0cRmOoVYYF6abFclzOW3TmbvZC0qt/i3+zirJejKZkXA6PIQ4hrMSijDSfdSWufio6s7eEHpfe3VJdXc4IwwlFV+SzHonOLa1wq1FLQwUtrPx3JybSD70s+OVqvp+uQxyCnCyZoY7pWxy6jApc5wTf7YnjspLLUf20tuwe3tKR3/x+y99gnBO7W4dmRyVM5vaC/jxm97NIntjxbEQpBkaT+I4RYEnAtn46fAaOFG7W9u9c48PLOX+/JYG2qFXDBW1tRzygHeLMW2VgMc3RVjzxTFvVAPJKOunBzmSwHQM43OP6V8el6zjPeExlHl8y2r+6Uv6UNkTygzXzZWf7VKnjY4KMGhuascGz8kLaPrLSWYSCtN7XBqwYJXh/EprSbwd3wGESNlVvi7CLGA+t/LVd6YuekxLgV7UszaEeDnca38EPPzPQchP+SkpuQ7ZYxs=
  file_glob: true
  file: funz-client*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
